### PR TITLE
Ignore files when exporting package

### PR DESCRIPTION
**Pull request by simonschaufi**
This commit is part of a campaign to reduce the amount of data transferred to save global bandwidth and reduce the amount of CO2. See https://github.com/Codeception/Codeception/pull/5527 for more info.

### CODE REVIEW

**Comment by simonschaufi** [comment]
@reinink can this be merged please? The travis error is not because of me ;)

**Comment by simonschaufi** [comment]
@reinink ping

**Comment by tgalopin** [comment]
Replaced by https://github.com/thephpleague/glide/pull/305

**Comment by tgalopin** [comment]
Thanks for your PR!

**Pull request closed without merging**
