### PR TITLE
Added HHVM Badge.

### PR DESCRIPTION
**Pull request by h4cc**

### CODE REVIEW

**Comment by reinink** [comment]
So how do I get "fully tested" status? :)

**Comment by h4cc** [comment]
@reinink yep, no `allow_failures`.

**Comment by reinink** [comment]
Okay, I've removed that. How long till the badge updates? :)

**Comment by reinink** [comment]
Let me guess, all the package dependencies must also have `allow_failures` removed?

**Comment by h4cc** [comment]
A few minutes, Github limit of the service is currently reached:

> You have reached GitHub hour limit! Actual limit is: 5000

No, its just the content of the travis.yml file that is used.

**Comment by reinink** [comment]
Cool, good stuff!

**Comment by h4cc** [comment]
The badge went green! :+1:

**Comment by reinink** [comment]
Nice, thanks man!

**Pull request merged**
