### PR TITLE
Bump up min. PHP version to 7.2 and get test suite running again.

### PR DESCRIPTION
**Pull request by ADmad**
I chose PHP 7.2 as the minimum version to support as that's the version supported by current major versions of popular frameworks.  Also flysystem v2 is slated to be PHP 7.2+.

@reinink It seems you are unable to devote time to this project lately. It would be great if you could invite and give commit access to others who are interested in helping maintain / enhance this wonderful project.

### CODE REVIEW

**Comment by ADmad** [comment]
I can follow this up by adding some static analysis checks using tools pslam/phpstan.

**Comment by reinink** [comment]
Hey @ADmad, thanks so much for your efforts here.

Is there any particular reason you included the composer.lock file? I've generally left this out of my packages.

**Comment by ADmad** [comment]
> Is there any particular reason you included the composer.lock file? I've generally left this out of my packages.

I didn't include it, I dropped it :slightly_smiling_face:. It's already present on `master`.

**Comment by reinink** [comment]
Oh my, I need another coffee lol. ☕

**Comment by reinink** [comment]
Tagged: https://github.com/thephpleague/glide/releases/tag/1.6.0

**Pull request merged**
