### PR TITLE
Add "fill-max" resizing option

### PR DESCRIPTION
**Pull request by adrenth**
Added the "fill-max" resizing option to the version 1.x branch. So that users which kept stuck at version 1.x can use this resizing option.

The code was taken from PR #332 which is now part of version 2.x

### CODE REVIEW

**Comment by adrenth** [comment]
I have resolved the merge-conflict. Missed the notification a while ago.

**Comment by jackmcdade** [comment]
> Seems like this package is abandoned?

It definitely isn’t. There have been commits and releases recently.

**Comment by adrenth** [comment]
That’s great to hear. We’ll wait patiently then.

**Review by thomaspicquet — APPROVED** [review]

**Comment by ADmad** [comment]
Currently I am the only one maintaining this package and with the limited time I can spare I only look into bug fixes for the 1.x branch.

On a related note Intervention/image itself seems unmaintained with no activity since about 6 months.

**Comment by nlemoine** [comment]
> On a related note Intervention/image itself seems unmaintained with no activity since about 6 months.

Seems like [very active again](https://github.com/Intervention/image/releases) 🙌

**Comment by ADmad** [comment]
1.x won't be getting any new updates.

**Pull request closed without merging**
