### PR TITLE
#206: stretch-fill support

### PR DESCRIPTION
**Pull request by xor22h**
Adds support for feature request #206

### CODE REVIEW

**Comment by reinink** [comment]
Hey thanks for putting this together! I'll need to do some testing before merging it in.

I'm also not sure I'm sold on the name "stretch-fill", since it sounds like the image is not being stretched (distorted), but rather just scaled, yes?

It would also be great to have a test to go with this.

**Comment by xor22h** [comment]
@reinink yeah, i'm not sure about the title too. It works more like contain-fill :) It was just the behaviour and name suggested by #206;

Because now it works same as contain, just contain, makes image smaller (crops transparent sides), and this one just fills it with a background color making image being the same size as requested.

**Comment by reinink** [comment]
Understood, okay, let me think on this.

Fair warning, I'm busy this week, and on holidays next week, so it will likely be the week after. 👍

**Comment by xor22h** [comment]
I don't worry too much. I installed it from my own fork so i'm happy for myself :D just saw a related ticket :)

**Comment by tgalopin** [comment]
@reinink did you hve time to check this? I can have a look and merge if you're OK with it :)

**Comment by reinink** [comment]
@tgalopin Negative, never had a chance. Feel free to proceed.

Note, maybe of the terminology that I've used for Glide is based on Imgix's API. I found they've done a pretty good job with their API. Obviously it doesn't have to match exactly, but it might be good to have a peak at their docs for some inspiration here. 👍

**Comment by tgalopin** [comment]
Thanks for the tip, I'll have a look!

**Comment by ADmad** [comment]
Implemented with name "fill-max" in #332.

**Pull request closed without merging**
