### PR TITLE
Allow to configure temp directory

### PR DESCRIPTION
**Pull request by tgalopin**
Introduce the ability to configure the temporary directory used to store EXIF data. It's an adaptation of @jaapio work in https://github.com/thephpleague/glide/pull/165, thanks for the PR!

Replace https://github.com/thephpleague/glide/pull/165
Fixes https://github.com/thephpleague/glide/issues/156
Fixes https://github.com/thephpleague/glide/issues/186

### CODE REVIEW

**Comment by piotr-cz** [comment]
This looks great,
what do you think about adding `temp_dir` to ServerFactory default options with fallback value of `sys_get_temp_dir()`?

**Comment by tgalopin** [comment]
Good idea, I'll do that

**Comment by piotr-cz** [comment]
Thanks!

**Comment by piotr-cz** [comment]
It seems to me that this PR has never been published in any release yet

**Comment by tgalopin** [comment]
It is released in 2.0 but not in 1.x indeed. I'll release it when I have time (not this week)

**Comment by piotr-cz** [comment]
Thanks, I've migrated to 2.0

**Pull request merged**
